#!/bin/sh
#
#  Copyright (c) 2021,2022: Jacob.Lundqvist@gmail.com
#  License: MIT
#
#  Part of https://github.com/jaclu/man_asdf
#
#  Version: 1.0.4 2022-04-14
#

#  shellcheck disable=SC1007
CURRENT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

conf_file="$CURRENT_DIR/.destination"

if [ ! -f "$conf_file" ]; then
    echo "If you put a conf_file dir in the file $conf_file"
    echo "This deploy will use rsync and copy any updates to that location."
    echo "Example:"
    echo "  echo /usr/local/bin > $conf_file"
    exit 1
fi

d_dest="$(cat "$conf_file")"

if [ ! -d "$d_dest" ]; then
    echo "ERROR: The directory mentioned in .destination does not exist"
    echo "       Supplied destination: $d_dest"
    exit 1
fi

echo
echo "-----   Deploying man_asdf   -----"

cmd_man="man_asdf"
f_src="$CURRENT_DIR/$cmd_man"
f_man_asdf="$d_dest/$cmd_man"
f_man="$d_dest"/man

rsync -ahP --inplace  "$f_src" "$f_man_asdf" | grep -v "sending incremental file list"
if [ -f "$f_man_asdf" ]; then
    ln -sf "f_man_asdf" "$f_man"
    [ -L "$f_man" ] || {
        echo "ERROR: failed to create symbolick link $f_man"
        exit 1
    }
else
    echo "ERROR: failed deploy to: $f_man_asdf"
    exit 1
fi
