#!/bin/sh
#
#  Copyright (c) 2021,2022: Jacob.Lundqvist@gmail.com
#  License: MIT
#
#  Part of https://github.com/jaclu/man_asdf
#
#  Version: 1.0.1 2022-04-14
#

if [ ! -f ".destination" ]; then
    echo "If you put a destination dir in the file .destination"
    echo "This deploy will use rsync and copy any updates to that location."
    echo "Example:"
    echo "  echo /usr/local/bin > .destination"
    exit 1
fi

dest="$(cat .destination)"

if [ ! -d "$dest" ]; then
    echo "ERROR: The directory mentioned in .destination does not exist"
    echo "       Supplied destination: $dest"
    exit 1
fi


echo
echo "-----   Deploying man_asdf   -----"


rsync -ahP --inplace  man_asdf "$dest"
